services:
  web:
    image: something-webbed
    build: .
    ports:
      - "8080:8080"
    environment:
      - API_URL=https://your/api
    volumes:
      - ./mnt:/app/mnt
      - ./mnt/upload:/app/api/rest/public/images
