services:
  web:
    image: something-webbed
    build: .
    ports:
      - "420:420"
    environment:
      - API_URL=https://localhost/api
      - CONTAINER_PORT=420
    volumes:
      - ./mnt:/app/mnt
      - ./mnt/upload:/app/api/rest/public/images
