services:
  web:
    image: trevorjmartin/something-webbed
    ports:
      - "8080:8080"
    environment:
      - API_URL=https://yourdomain/api
    volumes:
      - ./mnt:/app/mnt
      - ./mnt/upload:/app/api/rest/public/images
