services:
  web:
    image: something-webbed:latest
    ports:
      - 80:80
    environment:
      - API_URL=http://localhost/api
      - CONTAINER_PORT=80
    volumes:
      - ./mnt:/app/mnt
      - ./mnt/upload:/app/api/rest/public/images
